name: penicillisolver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0  
  flutter_local_notifications: ^17.2.4 
  camera: ^0.11.0+2
  firebase_core: ^2.13.0
  firebase_auth: ^4.8.1
  cloud_firestore: ^4.9.0
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  image_cropper: ^8.1.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fb.png
    - assets/google.png
    - assets/logo1.png
    - assets/logo2.png
    - assets/x.png
    - assets/josh.png
    - assets/lupa.png
    - assets/notif.png
    - assets/berhasil.png
    - assets/profile.png
    - assets/bakteri.png
    - assets/sakit.png
    - assets/pola.png
    - assets/lupa2.gif
    - assets/user1.png
    - assets/notif.gif
    - assets/polakuman.png
    - assets/jawinpp.png
