name: penicillisolver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0  
  flutter_local_notifications: ^18.0.1 
  camera: ^0.11.0+2
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.9.0
  cryptography: ^2.7.0
  flutter_dotenv: ^5.2.1
  sqflite: ^2.4.1
  image_cropper: ^8.1.0
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png"
  adaptive_icon_foreground: "assets/icon/logo.png" 
  adaptive_icon_background: "#ffffff"

min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/fb.png
    - assets/google.png
    - assets/logo1.png
    - assets/logo2.png
    - assets/x.png
    - assets/josh.png
    - assets/berhasil.png
    - assets/profile.png
    - assets/bakteri.png
    - assets/sakit.png
    - assets/pola.png
    - assets/lupa2.gif
    - assets/user1.png
    - assets/polakuman.png
    - assets/jawinpp.png
    - assets/email.gif
    - .env
